# Generated by Django 2.1.7 on 2019-03-01 16:53

from django.db import migrations, models
import lda.models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalquery',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=lda.models.productFile),
        ),
    ]
