# Generated by Django 2.1.7 on 2019-03-01 18:38

from django.db import migrations, models
import django.db.models.deletion
import lda.models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0002_canalquery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=lda.models.productFile)),
            ],
        ),
        migrations.RemoveField(
            model_name='canalquery',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='canalquery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lda.CanalQuery'),
        ),
    ]
