# Generated by Django 2.1.7 on 2019-03-01 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0004_remove_photo_canalquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='canalquery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lda.CanalQuery'),
            preserve_default=False,
        ),
    ]
