# Generated by Django 2.1.7 on 2019-03-02 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lda', '0005_photo_canalquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, default='admin_new', max_length=255)),
                ('admin_password', models.CharField(default='pass', max_length=255)),
                ('admin_pubkey', models.CharField(blank=True, max_length=255)),
                ('admin_privkey', models.CharField(blank=True, max_length=255)),
                ('admin_authority', models.CharField(default='sih_central', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default='8295729539', max_length=255)),
                ('otp', models.CharField(blank=True, default='1000', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='canalquery',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='authority',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canalquery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='phone_number',
            field=models.CharField(blank=True, default='8295729539', max_length=255),
        ),
        migrations.AddField(
            model_name='canalquery',
            name='status_choice',
            field=models.CharField(default='Pending', max_length=9),
        ),
        migrations.AlterField(
            model_name='photo',
            name='canalquery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='lda.CanalQuery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='media'),
        ),
    ]
