# Generated by Django 2.1.7 on 2019-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0007_canalquery_water_body_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone_number', models.CharField(blank=True, default='7302202200', max_length=255)),
                ('user_pubkey', models.CharField(max_length=255)),
                ('user_privkey', models.CharField(max_length=255)),
            ],
        ),
    ]
