# Generated by Django 2.1.7 on 2019-03-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0008_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='canalquery',
            field=models.IntegerField(default=-1),
        ),
    ]
