# Generated by Django 2.1.7 on 2019-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0009_auto_20190302_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(default='0.0', max_length=255)),
                ('longitude', models.CharField(default='0.0', max_length=255)),
                ('water_body_type', models.CharField(default='Canal', max_length=255)),
                ('authority_name', models.CharField(default='sih_central', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='is_reviewer',
            field=models.BooleanField(default=False),
        ),
    ]
