# Generated by Django 2.1.7 on 2019-03-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lda', '0010_auto_20190302_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canalquery',
            name='owner',
        ),
        migrations.DeleteModel(
            name='CanalQuery',
        ),
    ]
